from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa



revision: str = '2972fd7b03a3'
down_revision: Union[str, None] = 'a635703a6b55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_capsules', sa.Column('content_type', sa.String(length=10), nullable=True, comment='自定义内容类型：TEXT 或 IMAGE'))
    op.add_column('time_capsules', sa.Column('file_path', sa.String(length=500), nullable=True, comment='上传文件路径（图片类型时使用）'))
    op.add_column('time_capsules', sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小（字节）'))
    op.add_column('time_capsules', sa.Column('mime_type', sa.String(length=100), nullable=True, comment='文件 MIME 类型'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_capsules', 'mime_type')
    op.drop_column('time_capsules', 'file_size')
    op.drop_column('time_capsules', 'file_path')
    op.drop_column('time_capsules', 'content_type')
    # ### end Alembic commands ###
