from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa



revision: str = '66137253b388'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('big_tag', sa.Enum('KNOWLEDGE_POINT', 'FREEFORM_NOTE', 'INSPIRATION_FLASH', 'DECISION_DILEMMA', name='bigtag'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'big_tag')
    # ### end Alembic commands ###
