from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'dcaa1b9086ad'
down_revision: Union[str, None] = '66137253b388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('favorite', sa.Boolean(), nullable=True))
    op.execute("UPDATE memories SET favorite = 0 WHERE favorite IS NULL")
    with op.batch_alter_table('memories') as batch_op:
        batch_op.alter_column('favorite', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'favorite')
    # ### end Alembic commands ###
