from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e4a5f1b2c3d4'
down_revision: Union[str, None] = 'dcaa1b9086ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('file_size', sa.Float(), nullable=True))
    op.add_column('memories', sa.Column('mime_type', sa.String(100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'mime_type')
    op.drop_column('memories', 'file_size')
    # ### end Alembic commands ###