from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa



revision: str = 'ef300e1cd3c9'
down_revision: Union[str, None] = 'e4a5f1b2c3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('privacy_status', sa.Enum('ANALYZE', 'STORE', 'LOCKED', name='privacystatus'), nullable=False, server_default='ANALYZE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'privacy_status')
    # ### end Alembic commands ###
